### PR TITLE
Created Swodlr API test cases

### PR DESCRIPTION
**Pull request by Phoeneix**
Github Issue:  https://github.com/podaac/swodlr/issues/44

### Description

Adding Graphql API test cases for SWODLR

### Overview of work done

    - Created interface for Product, Raster Definition, Status and Current User
    - Added error injection for the graphql interface
    - Created 6 new passing test cases for Product, Raster Definition, Status and Current User calls
    - Created 14 new authantication error test cases for Product, Raster Definition, Status and Current User calls
    - Created 48 new type and value edge case test cases

### Overview of verification done

https://github.com/podaac/swodlr-functional-tests/actions/runs/7025976733

### Overview of integration done

_Explain how this change was integration tested. Provide screenshots or logs if appropriate. An example of this would be a local Harmony deployment._

## PR checklist:

* [ ] Linted
* [ ] Updated unit tests
* [x] Updated changelog
* [ ] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Review by frankinspace — COMMENTED** [review]
The tests cases look good but they are all failing because it looks like they are getting html content returned instead of json content. Do we know why that is?

**Comment by joshgarde** [comment]
@frankinspace It's because we don't have UAT public yet so S3's default response is to return our 404 html which happens to also be the index page.

**Comment by viviant100** [comment]
Once swodlr API is deployed to **_UAT_** venue via **_automated deployment_** (CICD team), we'll run the automated tests in UAT to verify they work and then merge this PR.

**Review by viviant100 — APPROVED** [review]
@frankinspace reviewed the PR. @viviant100 verified the tests worked in UAT (1/10/24).

**Pull request merged**
